# -*- coding: utf-8 -*-
"""Survey demo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uzQTlItzOEb678rPDSmQUlHVQ56fIDPs
"""

pip install ipywidgets

import pandas as pd
# Example logic:
# df = pd.DataFrame([new_data_dict])
# df.to_csv('baseline_results.csv', mode='a', header=False)

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 1. Custom Styling for a "Sleek" appearance
display(HTML("""
    <style>
        .widget-label { font-weight: bold; color: #2c3e50; }
        .survey-container { border: 1px solid #dcdde1; padding: 20px; border-radius: 10px; background-color: #f9f9f9; }
        .header-style { color: #1a5fb4; font-family: 'Arial', sans-serif; }
    </style>
"""))

# 2. Survey Questions Data
questions = [
    ("Goal 1: Nicotine pouches are significantly less harmful than cigarettes.", "risk_perception"),
    ("Goal 1: I believe nicotine pouches are 'tobacco-free' and therefore safe.", "safety_bias"),
    ("Goal 2: Most people in my school use nicotine pouches daily.", "social_norm"),
    ("Goal 2: It is socially awkward to say 'no' if a friend offers a pouch.", "peer_pressure")
]

# 3. UI Components
title = widgets.HTML("<h2 class='header-style'>Youth Nicotine Perception Survey (Baseline)</h2>")
instruction = widgets.HTML("<p>Please rate your agreement with the following statements (1 = Strongly Disagree, 5 = Strongly Agree)</p>")

# Dictionary to store responses
responses = {}

# Build the layout
survey_items = []
for q_text, q_id in questions:
    label = widgets.Label(value=q_text)
    slider = widgets.IntSlider(value=3, min=1, max=5, step=1, layout=widgets.Layout(width='50%'))
    responses[q_id] = slider
    survey_items.append(widgets.VBox([label, slider], layout=widgets.Layout(margin='10px 0px')))

# Qualitative Section
qual_label = widgets.Label(value="What is the first thing you think of when you see 'tobacco-free' on a tin?")
qual_text = widgets.Textarea(placeholder='Type your thoughts here...', layout=widgets.Layout(width='80%', height='80px'))
responses['qualitative'] = qual_text

# Submit Button
submit_btn = widgets.Button(description="Submit Response", button_style='primary', layout=widgets.Layout(margin='20px 0px'))
output = widgets.Output()

def on_submit(b):
    with output:
        clear_output()
        # In a real scenario, you would append this to a CSV or Database
        print("✅ Data recorded locally. Summary of response:")
        for key, widget in responses.items():
            print(f"- {key}: {widget.value}")
        print("\nThank you for participating! Your response is anonymous.")

submit_btn.on_click(on_submit)

# 4. Display Everything
survey_ui = widgets.VBox([
    title,
    instruction,
    *survey_items,
    widgets.VBox([qual_label, qual_text]),
    submit_btn,
    output
], layout=widgets.Layout(padding='20px', border='1px solid #bdc3c7', border_radius='8px'))

display(survey_ui)

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 1. Professional Styling - Using a "Workshop-Yellow" theme for visibility
display(HTML("""
    <style>
        .midline-header { color: #856404; background-color: #fff3cd; padding: 10px; border-radius: 5px; font-family: 'Segoe UI', sans-serif; }
        .workshop-box { border-left: 5px solid #ffc107; padding: 15px; margin: 10px 0; background-color: #ffffff; }
        .widget-label { font-weight: 600; margin-bottom: 5px; }
    </style>
"""))

# 2. Midline Questions: Measuring Workshop Impact & Intent
midline_questions = [
    ("How credible did you find the information shared in the workshop?", "credibility"),
    ("After the workshop, I view 'tobacco-free' labels more skeptically.", "dissonance"),
    ("I have discussed the campaign's 'industry manipulation' message with friends.", "peer_discussion"),
    ("I plan to use the campaign microsite to learn more about nicotine risks.", "intent_to_act")
]

# 3. UI Components
title = widgets.HTML("<h2 class='midline-header'>Midline Evaluation: Campaign Pulse Check (Month 6)</h2>")
municipality = widgets.Dropdown(
    options=['Kalmar', 'Lund', 'Umeå', 'Control Group'],
    description='Location:',
    style={'description_width': 'initial'}
)

# Container for layout
responses = {}
survey_items = []

for q_text, q_id in midline_questions:
    label = widgets.Label(value=q_text)
    # Using a 1-10 scale for Midline to get more granular "Leading Indicator" data
    slider = widgets.IntSlider(value=5, min=1, max=10, layout={'width': '70%'})
    responses[q_id] = slider
    survey_items.append(widgets.VBox([label, slider], layout={'margin': '15px 0'}))

# Special Section: Gatekeeper Leading Indicators
gk_label = widgets.Label(value="For Adults: Have you downloaded the 'Conversation Guides' from the microsite?")
gk_check = widgets.RadioButtons(options=['Yes', 'Not yet, but I know where they are', 'No', 'I didn\'t know they existed'])
responses['gk_resource_access'] = gk_check

# Submit Button
submit_btn = widgets.Button(description="Submit Midline Data", button_style='warning', layout={'margin': '20px 0'})
output = widgets.Output()

def on_submit(b):
    with output:
        clear_output()
        print(f"📍 Midline Data Logged for {municipality.value}")
        print("Summary of Key Metrics (1-10 scale):")
        for k, v in responses.items():
            print(f"- {k}: {v.value}")
        print("\nCreative Calibration: If scores are < 5, trigger creative review protocol.")

submit_btn.on_click(on_submit)

# 4. Display
midline_ui = widgets.VBox([
    title,
    municipality,
    widgets.VBox(survey_items, layout={'margin': '20px 0'}),
    widgets.VBox([gk_label, gk_check], layout={'padding': '10px', 'border': '1px solid #ddd'}),
    submit_btn,
    output
], layout={'padding': '25px', 'border': '2px solid #ffc107', 'border_radius': '10px'})

display(midline_ui)

import ipywidgets as widgets
from IPython.display import display, HTML, clear_output

# 1. Professional Styling
display(HTML("""
    <style>
        .endline-header { color: #d35400; font-family: 'Helvetica', sans-serif; border-bottom: 2px solid #d35400; }
        .section-box { border: 1px solid #bdc3c7; padding: 15px; margin: 10px 0; border-radius: 5px; background-color: #ffffff; }
        .widget-label { font-size: 14px; }
    </style>
"""))

# 2. Endline Specific Questions
# We include behavioral follow-ups and Goal 3 (Gatekeeper activation)
student_questions = [
    ("Goal 1: I now feel I have enough information to judge the risks of nicotine pouches.", "informed_status"),
    ("Goal 1: I believe the nicotine industry deliberately uses flavors to attract young people.", "industry_awareness"),
    ("Goal 2: In the last 6 months, I have seen fewer people using pouches in school areas.", "perceived_reduction"),
    ("Goal 2: I feel confident saying 'no' to nicotine products in a social setting.", "refusal_efficacy")
]

# 3. UI Components
title = widgets.HTML("<h2 class='endline-header'>Campaign Endline Evaluation (Month 12)</h2>")
role_toggle = widgets.ToggleButtons(
    options=['Student (13-18)', 'Teacher/Nurse', 'Parent'],
    description='Your Role:',
    button_style='info'
)

# Container for dynamic questions
survey_content = widgets.VBox()
responses = {}

def build_survey(change):
    items = []
    responses.clear()

    if role_toggle.value == 'Student (13-18)':
        for q_text, q_id in student_questions:
            label = widgets.Label(value=q_text)
            slider = widgets.SelectionSlider(options=['Strongly Disagree', 'Disagree', 'Neutral', 'Agree', 'Strongly Agree'], layout={'width': '60%'})
            responses[q_id] = slider
            items.append(widgets.VBox([label, slider]))

    else: # Gatekeeper Role
        q_text = "Goal 3: Have you initiated a conversation about nicotine with a young person in the last 60 days?"
        check = widgets.Dropdown(options=['Yes, multiple times', 'Yes, once', 'No, but I planned to', 'No'], value='No')
        responses['behavioral_action'] = check

        q_conf = "Goal 3: How confident do you feel using the Folkhälsomyndigheten conversation guides?"
        conf_slider = widgets.IntSlider(min=1, max=10, value=5)
        responses['confidence_score'] = conf_slider

        items.append(widgets.VBox([widgets.Label(value=q_text), check]))
        items.append(widgets.VBox([widgets.Label(value=q_conf), conf_slider]))

    # Common Qualitative Field
    qual_label = widgets.Label(value="What is the most memorable part of the 'They Designed It to Hook You' campaign?")
    qual_text = widgets.Textarea(layout={'width': '80%'})
    responses['memory_recall'] = qual_text
    items.append(widgets.VBox([qual_label, qual_text]))

    survey_content.children = items

role_toggle.observe(build_survey, names='value')
build_survey(None) # Initialize

# Submit Logic
submit_btn = widgets.Button(description="Complete Evaluation", button_style='success', layout={'margin': '20px 0'})
output = widgets.Output()

def on_submit(b):
    with output:
        clear_output()
        print("📊 Endline Data Captured Successfully.")
        print(f"Role: {role_toggle.value}")
        for k, v in responses.items():
            print(f"- {k}: {v.value}")
        print("\nThis data will be used for the final Difference-in-Differences report.")

submit_btn.on_click(on_submit)

# 4. Display
display(widgets.VBox([title, role_toggle, survey_content, submit_btn, output], layout={'padding': '20px'}))